#!groovy
echo 'Start'
def lib = libraryResource '../../'
echo 'Lib=' + lib 
//@Library(['acme', 'helloWorld', 'master']) _

def helloWorld = load('../../var/helloWorld.groovy')
/*** Build the eboutique project components ***/
helloWorld("Joe")
stage concurrency: 1, name: 'Build'
/*master {
 helloWorld("Joe")
 acme.foo = "5";
 echo acme.foo;
 acme.say "Joe";
}*/
